"""add theme and sound_enabled to creator

Revision ID: 0b9b2e829ffa
Revises: 9483af05dd5b
Create Date: 2026-08-08 13:10:27.664520

Autogenerated, then hand-edited in one place, for the same reason the T011 migration was:
autogenerate emits `sa.Enum(...)` inline, which makes Postgres create the `theme` type implicitly on
upgrade while the generated `downgrade` only drops the column — the type survives, and the *second*
`upgrade` fails with "type theme already exists". `specs/002-pixel-arcade-skin/data-model.md` names
this trap explicitly. The type is created and dropped here, explicitly, with `create_type=False` on
the column so nothing does it implicitly.

`server_default` on both columns matches `data-model.md`: both columns are `NOT NULL` with a default
rather than nullable, so an existing `creator` row (there is exactly one, INV-1) gets `dark` /
`false` rather than a constraint violation.
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0b9b2e829ffa"
down_revision: str | None = "9483af05dd5b"
branch_labels: str | None = None
depends_on: str | None = None

# create_type=False so the type is created and dropped only where this file says so, rather than
# implicitly as a side effect of add_column.
theme_enum = postgresql.ENUM("dark", "light", name="theme", create_type=False)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    theme_enum.create(bind, checkfirst=False)

    op.add_column(
        "creator",
        sa.Column("theme", theme_enum, server_default="dark", nullable=False),
    )
    op.add_column(
        "creator",
        sa.Column(
            "sound_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )


def downgrade() -> None:
    """Downgrade schema.

    The enum is dropped last: it is not owned by the column, and dropping it before the column that
    uses it fails. Forgetting it entirely is what makes a second `upgrade` fail.
    """
    op.drop_column("creator", "sound_enabled")
    op.drop_column("creator", "theme")

    bind = op.get_bind()
    theme_enum.drop(bind, checkfirst=False)
