"""add trip destination photograph

Revision ID: 9e79a029a750
Revises: 0b9b2e829ffa
Create Date: 2026-08-14 14:18:46.657913

Autogenerated, then hand-edited in one place, the same trap the two prior migrations in this
directory both name: autogenerate emits `sa.Enum(...)` inline, which makes Postgres create the
`tripstatus`/`destinationstatus` types implicitly on upgrade while the generated `downgrade` only
drops the tables — the types survive, and the *second* `upgrade` fails with "type ... already
exists". Both are created and dropped here, explicitly, with `create_type=False` on the columns so
nothing does it implicitly.

`data-model.md`'s three indexes (`ix_destination_trip_id`, `ix_destination_status`,
`ix_photograph_destination_id`) and both `ON DELETE CASCADE` foreign keys came out of autogenerate
unchanged — `Destination.trip_id`/`Photograph.destination_id` already declare them in
`app/models.py`.
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "9e79a029a750"
down_revision: str | None = "0b9b2e829ffa"
branch_labels: str | None = None
depends_on: str | None = None

# create_type=False so the types are created and dropped only where this file says so, rather than
# implicitly as a side effect of create_table.
trip_status_enum = postgresql.ENUM(
    "wishlist",
    "planned",
    "booked",
    "upcoming",
    "traveling",
    "completed",
    name="tripstatus",
    create_type=False,
)
destination_status_enum = postgresql.ENUM(
    "visited", "planned", "wishlist", name="destinationstatus", create_type=False
)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    trip_status_enum.create(bind, checkfirst=False)
    destination_status_enum.create(bind, checkfirst=False)

    op.create_table(
        "trip",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("status", trip_status_enum, server_default="wishlist", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "destination",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("status", destination_status_enum, server_default="wishlist", nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["trip_id"], ["trip.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_destination_status", "destination", ["status"], unique=False)
    op.create_index("ix_destination_trip_id", "destination", ["trip_id"], unique=False)

    op.create_table(
        "photograph",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("destination_id", sa.Integer(), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["destination_id"], ["destination.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_photograph_destination_id", "photograph", ["destination_id"], unique=False)


def downgrade() -> None:
    """Downgrade schema.

    Drops the enum types last. They are not owned by any table, so dropping them before the
    columns that use them fails, and forgetting them entirely is what makes a second upgrade fail.
    """
    op.drop_index("ix_photograph_destination_id", table_name="photograph")
    op.drop_table("photograph")

    op.drop_index("ix_destination_trip_id", table_name="destination")
    op.drop_index("ix_destination_status", table_name="destination")
    op.drop_table("destination")

    op.drop_table("trip")

    bind = op.get_bind()
    destination_status_enum.drop(bind, checkfirst=False)
    trip_status_enum.drop(bind, checkfirst=False)
