"""create content_item and creator

Revision ID: 9483af05dd5b
Revises:
Create Date: 2026-07-30 13:32:11.845751

Autogenerated, then hand-edited in three places. All three are things autogenerate cannot produce,
and all three are specified in data-model.md:

1. **The enum types are created and dropped explicitly.** Autogenerate emits `sa.Enum(...)` inside
   `create_table`, which makes Postgres create the type implicitly on upgrade — but the generated
   `downgrade` only drops the table. The type survives, and the next `upgrade` fails with
   "type platform already exists". The asymmetry is invisible until someone actually downgrades.

2. **The INV-1 and INV-2 CHECK constraints.** Alembic does not compare CHECK constraints at all, so
   these will never be autogenerated. data-model.md requires the invariants expressible in SQL to
   live in the table as well as at the API boundary, because a check that exists only in
   application code is one a future migration script can bypass.

3. **The backlog partial index** (`created_at DESC WHERE scheduled_date IS NULL`).

Points 2 and 3 are also declared on `ContentItem.__table_args__`. That is not duplication for its
own sake: Alembic *does* compare indexes, so with the index living only here, `alembic check`
reports drift and the next autogenerated revision drops it.
"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "9483af05dd5b"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None

# create_type=False so the types are created and dropped only where this file says so, rather than
# implicitly as a side effect of create_table.
platform_enum = postgresql.ENUM(
    "tiktok", "instagram", "youtube", name="platform", create_type=False
)
status_enum = postgresql.ENUM("idea", "draft", "posted", name="status", create_type=False)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    platform_enum.create(bind, checkfirst=False)
    status_enum.create(bind, checkfirst=False)

    op.create_table(
        "content_item",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("hook", sa.String(length=500), nullable=True),
        sa.Column("platform", platform_enum, nullable=True),
        sa.Column("scheduled_date", sa.Date(), nullable=True),
        sa.Column("status", status_enum, server_default="idea", nullable=False),
        sa.Column("published_url", sa.String(length=2048), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        # INV-1 (FR-009, FR-009a): a platform is required past `idea`. One constraint covers both
        # requirements — advancing without a platform and clearing a platform while advanced are
        # both just attempts to violate it.
        sa.CheckConstraint(
            "status = 'idea' OR platform IS NOT NULL",
            name="ck_content_item_platform_required_past_idea",
        ),
        # INV-2 (FR-005): NOT NULL alone permits '', and an item whose title is a space is
        # indistinguishable from a bug in the capture sheet.
        sa.CheckConstraint("length(trim(title)) > 0", name="ck_content_item_title_not_blank"),
    )

    # Every calendar read is a date-range query on this column.
    op.create_index(
        "ix_content_item_scheduled_date", "content_item", ["scheduled_date"], unique=False
    )
    # Cheap, and the pipeline view groups by it.
    op.create_index("ix_content_item_status", "content_item", ["status"], unique=False)
    # The backlog query (FR-011): undated items, newest first. Partial, because dated items are
    # never returned by it — which is most of the table once the calendar is in use.
    op.create_index(
        "ix_content_item_backlog",
        "content_item",
        [sa.text("created_at DESC")],
        unique=False,
        postgresql_where=sa.text("scheduled_date IS NULL"),
    )

    op.create_table(
        "creator",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )


def downgrade() -> None:
    """Downgrade schema.

    Drops the enum types last. They are not owned by either table, so dropping them before the
    column that uses them fails, and forgetting them entirely is what makes a second upgrade fail.
    """
    op.drop_table("creator")
    op.drop_index("ix_content_item_backlog", table_name="content_item")
    op.drop_index("ix_content_item_status", table_name="content_item")
    op.drop_index("ix_content_item_scheduled_date", table_name="content_item")
    op.drop_table("content_item")

    bind = op.get_bind()
    status_enum.drop(bind, checkfirst=False)
    platform_enum.drop(bind, checkfirst=False)
