"""add category to destination

Revision ID: a3dc458e18a6
Revises: b2e53f7a1c94
Create Date: 2026-08-23 11:41:55.333493

Autogenerated, then hand-edited for the same trap every enum-column migration in this file names:
autogenerate emits `sa.Enum(...)` inline, which makes Postgres create the `destinationcategory` type
implicitly on upgrade while the generated `downgrade` only drops the column — the type survives, and
a second `upgrade` fails with "type destinationcategory already exists". The type is created and
dropped here, explicitly, with `create_type=False` on the column so nothing does it implicitly.

Nullable, no `server_default` — unlike `theme`/`status`, which are `NOT NULL` with a real default,
`category` has no meaningful default: most places start uncategorized and are tagged later from the
Destination sheet (added outside the normal spec process, at the owner's explicit instruction — see
`specs/003-travel-map/spec.md`'s Assumptions section for the amendment note).
"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a3dc458e18a6'
down_revision: Union[str, Sequence[str], None] = 'b2e53f7a1c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# create_type=False so the type is created and dropped only where this file says so, rather than
# implicitly as a side effect of add_column.
category_enum = postgresql.ENUM(
    "food", "sightseeing", "nature", "stay", name="destinationcategory", create_type=False
)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    category_enum.create(bind, checkfirst=False)

    op.add_column("destination", sa.Column("category", category_enum, nullable=True))


def downgrade() -> None:
    """Downgrade schema.

    The enum is dropped last: it is not owned by the column, and dropping it before the column that
    uses it fails. Forgetting it entirely is what makes a second `upgrade` fail.
    """
    op.drop_column("destination", "category")

    bind = op.get_bind()
    category_enum.drop(bind, checkfirst=False)
